- name: Docker Build and Upload to AWS ECR
  uses: vitr/actions-build-and-upload-to-ecs@v1.0.0
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: vitr/actions-build-and-upload-to-ecs@master
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: docker/govtech
          region: ap-southeast-1
          tags: latest,${{ github.sha }}
          create_repo: false
